version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicaset123456
      MONGODB_DATABASE: nest
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
    
volumes:
  mongodb_data:
    driver: local
